### ISSUE TITLE
Unexpected EOF at line 1 column 2 of the JSON5 data

### ISSUE THREAD

**Issue by apingault** [richie5um/vscode-sort-json#11]
Hello,

First I want to thank you for this neat package !

Sadly, the extension is failing on my setup on any json file with the following message in the debug console:
```js
[Extension Host] SyntaxError: Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
	at error (~/.vscode/extensions/richie5um2.vscode-sort-json-1.9.0/node_modules/json5/lib/json5.js:56:25)
	at word (~/.vscode/extensions/richie5um2.vscode-sort-json-1.9.0/node_modules/json5/lib/json5.js:393:13)
	at value (~/.vscode/extensions/richie5um2.vscode-sort-json-1.9.0/node_modules/json5/lib/json5.js:493:56)
	at Object.parse (~/.vscode/extensions/richie5um2.vscode-sort-json-1.9.0/node_modules/json5/lib/json5.js:508:18)
	at Object.textToJSON (~/.vscode/extensions/richie5um2.vscode-sort-json-1.9.0/lib/sort-json-utils.js:5:23)
	at sortActiveSelectionInternal (~/.vscode/extensions/richie5um2.vscode-sort-json-1.9.0/lib/sort-json.js:71:30)
	at sortActiveSelection (~/.vscode/extensions/richie5um2.vscode-sort-json-1.9.0/lib/sort-json.js:43:13)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:334339)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:423958)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280554)
```

This is on bare settings.json file containing only two entries:
```json
{
    "window.restoreWindows": "all",
    "editor.formatOnType": true
}
```

As I was using an insider build with quite a lot of extensions/settings tweak I've installed a fresh vscode without any other extensions installed to make sure it's not coming from a weird interaction with other extensions. 

I am running this on an OSX 10.12 machine.

Hope this can be resolved,
Cheers

**Comment by richie5um** [comment]
Thanks for the 'thanks' :) 

Please can you confirm which version of VSCode you are now running?

I'm on a 10.12 macOS too, so hopefully I'll be able to reproduce.

PS: Sadly I'm mostly doing .Net dev on Windows at the moment, so have been using VSCode as much recently :(.

**Comment by apingault** [comment]
Yeah, fast answer!

I am running last version of both apps (at least it does not propose me any updates):
VSCode `Version 1.16.1 (1.16.1)`
VSCode-insideres: `Version 1.17.0-insider (1.17.0-insider)`

**Comment by richie5um** [comment]
Are you selecting the text before running 'sort json'? JSON-Sort only sorts the selected text.

[The only way I can get the same error is when I don't select any text]

**Comment by apingault** [comment]
I'm feeling quite foolish now, I guess I was somehow mis-selecting the text (like not selecting the enclosing curly brace or only part of an array )  as it works perfectly now!

Would it be possible to have something printed out in the output console in such case ?

Anyway it works beautifully as is, so thanks again for the extension!

**Comment by richie5um** [comment]
😄 

Good idea on the output.

I should probably also update the code so that if nothing is selected then it works on the whole file.

Thanks.

**Comment by richie5um** [comment]
If you update to the latest version (1.9.2) it should now work even if you don't select any text. Let me know if you have any issues.

**Comment by apingault** [comment]
Yes it works nicely on whole files now.
Thanks for the quick update!
